# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: prime_level.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11prime_level.proto\x12\x08freefire\"3\n\x04Users\x12+\n\tbasicinfo\x18\x01 \x03(\x0b2\x18.freefire.info\"-\n\x04info\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x13\n\x0bprime_level\x18\x33 \x01(\r\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'prime_level_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERS._serialized_start=32
  _USERS._serialized_end=83
  _INFO._serialized_start=85
  _INFO._serialized_end=130
# @@protoc_insertion_point(module_scope)